version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

jobs:
  build:
    working_directory: ~/Simple-App
    docker:
      - image: cimg/node:20.17
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm ci --unsafe-perm  # No sudo & safe permissions
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: run-tests
          command: npm test
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest -f Dockerfile .
      - run:
          name: Publish Docker Image
          command: docker push $IMAGE_NAME

  deploy:
    docker:
      - image: cimg/node:20.17  # Match Node version
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf Simple-App/; git clone https://github.com/timosmukoko/Simple-App.git; source Simple-App/deploy.sh"
